// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about/index.tsx";
import * as $5 from "./routes/account/_middleware.ts";
import * as $6 from "./routes/account/index.tsx";
import * as $7 from "./routes/account/manage.ts";
import * as $8 from "./routes/account/upgrade.ts";
import * as $9 from "./routes/admin/_middleware.ts";
import * as $10 from "./routes/admin/index.tsx";
import * as $11 from "./routes/api/book-list.ts";
import * as $12 from "./routes/api/book.ts";
import * as $13 from "./routes/api/list.ts";
import * as $14 from "./routes/api/stripe-webhooks.ts";
import * as $15 from "./routes/api/vote.ts";
import * as $16 from "./routes/blog/[slug].tsx";
import * as $17 from "./routes/blog/index.tsx";
import * as $18 from "./routes/books/AddBookToListForm.tsx";
import * as $19 from "./routes/books/[id].tsx";
import * as $20 from "./routes/books/index.tsx";
import * as $21 from "./routes/callback.ts";
import * as $22 from "./routes/comparePages.tsx";
import * as $23 from "./routes/discover/index.tsx";
import * as $24 from "./routes/feed.ts";
import * as $25 from "./routes/index.tsx";
import * as $26 from "./routes/item/[id].tsx";
import * as $27 from "./routes/lists/[id].tsx";
import * as $28 from "./routes/lists/index.tsx";
import * as $29 from "./routes/login.ts";
import * as $30 from "./routes/logout.ts";
import * as $31 from "./routes/my-lists/_middleware.ts";
import * as $32 from "./routes/my-lists/index.tsx";
import * as $33 from "./routes/new-book/_middleware.ts";
import * as $34 from "./routes/new-book/index.tsx";
import * as $35 from "./routes/new-list/_middleware.ts";
import * as $36 from "./routes/new-list/index.tsx";
import * as $37 from "./routes/pricing.tsx";
import * as $38 from "./routes/signin.ts";
import * as $39 from "./routes/signout.ts";
import * as $40 from "./routes/stats.tsx";
import * as $41 from "./routes/submit.tsx";
import * as $42 from "./routes/tracking/index.tsx";
import * as $43 from "./routes/uploaded-by-me-books/index.tsx";
import * as $44 from "./routes/uploads/ExampleTable.tsx";
import * as $45 from "./routes/uploads/index.tsx";
import * as $46 from "./routes/user/[username].tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/DeleteBookButton.tsx";
import * as $$2 from "./islands/DeleteListButton.tsx";
import * as $$3 from "./islands/DownloadCsvButton.tsx";
import * as $$4 from "./islands/EditBookForm.tsx";
import * as $$5 from "./islands/EditListForm.tsx";
import * as $$6 from "./islands/IpfsOpenButton.tsx";
import * as $$7 from "./islands/ListIpfsUploadButton.tsx";
import * as $$8 from "./islands/TableRow.tsx";
import * as $$9 from "./islands/TrackingChart.tsx";
import * as $$10 from "./islands/VoteButton.tsx";
import * as $$11 from "./islands/Wrapper.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about/index.tsx": $4,
    "./routes/account/_middleware.ts": $5,
    "./routes/account/index.tsx": $6,
    "./routes/account/manage.ts": $7,
    "./routes/account/upgrade.ts": $8,
    "./routes/admin/_middleware.ts": $9,
    "./routes/admin/index.tsx": $10,
    "./routes/api/book-list.ts": $11,
    "./routes/api/book.ts": $12,
    "./routes/api/list.ts": $13,
    "./routes/api/stripe-webhooks.ts": $14,
    "./routes/api/vote.ts": $15,
    "./routes/blog/[slug].tsx": $16,
    "./routes/blog/index.tsx": $17,
    "./routes/books/AddBookToListForm.tsx": $18,
    "./routes/books/[id].tsx": $19,
    "./routes/books/index.tsx": $20,
    "./routes/callback.ts": $21,
    "./routes/comparePages.tsx": $22,
    "./routes/discover/index.tsx": $23,
    "./routes/feed.ts": $24,
    "./routes/index.tsx": $25,
    "./routes/item/[id].tsx": $26,
    "./routes/lists/[id].tsx": $27,
    "./routes/lists/index.tsx": $28,
    "./routes/login.ts": $29,
    "./routes/logout.ts": $30,
    "./routes/my-lists/_middleware.ts": $31,
    "./routes/my-lists/index.tsx": $32,
    "./routes/new-book/_middleware.ts": $33,
    "./routes/new-book/index.tsx": $34,
    "./routes/new-list/_middleware.ts": $35,
    "./routes/new-list/index.tsx": $36,
    "./routes/pricing.tsx": $37,
    "./routes/signin.ts": $38,
    "./routes/signout.ts": $39,
    "./routes/stats.tsx": $40,
    "./routes/submit.tsx": $41,
    "./routes/tracking/index.tsx": $42,
    "./routes/uploaded-by-me-books/index.tsx": $43,
    "./routes/uploads/ExampleTable.tsx": $44,
    "./routes/uploads/index.tsx": $45,
    "./routes/user/[username].tsx": $46,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/DeleteBookButton.tsx": $$1,
    "./islands/DeleteListButton.tsx": $$2,
    "./islands/DownloadCsvButton.tsx": $$3,
    "./islands/EditBookForm.tsx": $$4,
    "./islands/EditListForm.tsx": $$5,
    "./islands/IpfsOpenButton.tsx": $$6,
    "./islands/ListIpfsUploadButton.tsx": $$7,
    "./islands/TableRow.tsx": $$8,
    "./islands/TrackingChart.tsx": $$9,
    "./islands/VoteButton.tsx": $$10,
    "./islands/Wrapper.tsx": $$11,
  },
  baseUrl: import.meta.url,
};

export default manifest;
