// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about/index.tsx";
import * as $5 from "./routes/account/_middleware.ts";
import * as $6 from "./routes/account/index.tsx";
import * as $7 from "./routes/account/manage.ts";
import * as $8 from "./routes/account/upgrade.ts";
import * as $9 from "./routes/api/book.ts";
import * as $10 from "./routes/api/bookList.ts";
import * as $11 from "./routes/api/list.ts";
import * as $12 from "./routes/api/stripe-webhooks.ts";
import * as $13 from "./routes/api/vote.ts";
import * as $14 from "./routes/blog/[slug].tsx";
import * as $15 from "./routes/blog/index.tsx";
import * as $16 from "./routes/books/AddBookToListForm.tsx";
import * as $17 from "./routes/books/[id].tsx";
import * as $18 from "./routes/books/index.tsx";
import * as $19 from "./routes/callback.ts";
import * as $20 from "./routes/dashboard/_middleware.ts";
import * as $21 from "./routes/dashboard/index.tsx";
import * as $22 from "./routes/dashboard/stats.tsx";
import * as $23 from "./routes/dashboard/users.tsx";
import * as $24 from "./routes/discover/index.tsx";
import * as $25 from "./routes/feed.ts";
import * as $26 from "./routes/index.tsx";
import * as $27 from "./routes/item/[id].tsx";
import * as $28 from "./routes/lists/[id].tsx";
import * as $29 from "./routes/lists/index.tsx";
import * as $30 from "./routes/my-lists/_middleware.ts";
import * as $31 from "./routes/my-lists/index.tsx";
import * as $32 from "./routes/new-book/_middleware.ts";
import * as $33 from "./routes/new-book/index.tsx";
import * as $34 from "./routes/new-list/_middleware.ts";
import * as $35 from "./routes/new-list/index.tsx";
import * as $36 from "./routes/notifications/[id].ts";
import * as $37 from "./routes/notifications/_middleware.ts";
import * as $38 from "./routes/notifications/index.tsx";
import * as $39 from "./routes/pricing.tsx";
import * as $40 from "./routes/private-books/index.tsx";
import * as $41 from "./routes/signin.ts";
import * as $42 from "./routes/signout.ts";
import * as $43 from "./routes/submit.tsx";
import * as $44 from "./routes/tracking/index.tsx";
import * as $45 from "./routes/uploads/ExampleTable.tsx";
import * as $46 from "./routes/uploads/index.tsx";
import * as $47 from "./routes/user/[login].tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/Chart.tsx";
import * as $$2 from "./islands/DeleteListButton.tsx";
import * as $$3 from "./islands/DownloadCsvButton.tsx";
import * as $$4 from "./islands/EditBookForm.tsx";
import * as $$5 from "./islands/EditListForm.tsx";
import * as $$6 from "./islands/PageInput.tsx";
import * as $$7 from "./islands/TableRow.tsx";
import * as $$8 from "./islands/UploadWrapper.tsx";
import * as $$9 from "./islands/VoteButton.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about/index.tsx": $4,
    "./routes/account/_middleware.ts": $5,
    "./routes/account/index.tsx": $6,
    "./routes/account/manage.ts": $7,
    "./routes/account/upgrade.ts": $8,
    "./routes/api/book.ts": $9,
    "./routes/api/bookList.ts": $10,
    "./routes/api/list.ts": $11,
    "./routes/api/stripe-webhooks.ts": $12,
    "./routes/api/vote.ts": $13,
    "./routes/blog/[slug].tsx": $14,
    "./routes/blog/index.tsx": $15,
    "./routes/books/AddBookToListForm.tsx": $16,
    "./routes/books/[id].tsx": $17,
    "./routes/books/index.tsx": $18,
    "./routes/callback.ts": $19,
    "./routes/dashboard/_middleware.ts": $20,
    "./routes/dashboard/index.tsx": $21,
    "./routes/dashboard/stats.tsx": $22,
    "./routes/dashboard/users.tsx": $23,
    "./routes/discover/index.tsx": $24,
    "./routes/feed.ts": $25,
    "./routes/index.tsx": $26,
    "./routes/item/[id].tsx": $27,
    "./routes/lists/[id].tsx": $28,
    "./routes/lists/index.tsx": $29,
    "./routes/my-lists/_middleware.ts": $30,
    "./routes/my-lists/index.tsx": $31,
    "./routes/new-book/_middleware.ts": $32,
    "./routes/new-book/index.tsx": $33,
    "./routes/new-list/_middleware.ts": $34,
    "./routes/new-list/index.tsx": $35,
    "./routes/notifications/[id].ts": $36,
    "./routes/notifications/_middleware.ts": $37,
    "./routes/notifications/index.tsx": $38,
    "./routes/pricing.tsx": $39,
    "./routes/private-books/index.tsx": $40,
    "./routes/signin.ts": $41,
    "./routes/signout.ts": $42,
    "./routes/submit.tsx": $43,
    "./routes/tracking/index.tsx": $44,
    "./routes/uploads/ExampleTable.tsx": $45,
    "./routes/uploads/index.tsx": $46,
    "./routes/user/[login].tsx": $47,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/Chart.tsx": $$1,
    "./islands/DeleteListButton.tsx": $$2,
    "./islands/DownloadCsvButton.tsx": $$3,
    "./islands/EditBookForm.tsx": $$4,
    "./islands/EditListForm.tsx": $$5,
    "./islands/PageInput.tsx": $$6,
    "./islands/TableRow.tsx": $$7,
    "./islands/UploadWrapper.tsx": $$8,
    "./islands/VoteButton.tsx": $$9,
  },
  baseUrl: import.meta.url,
};

export default manifest;
