// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/account/_middleware.ts";
import * as $4 from "./routes/account/index.tsx";
import * as $5 from "./routes/account/manage.ts";
import * as $6 from "./routes/account/upgrade.ts";
import * as $7 from "./routes/admin/_middleware.ts";
import * as $8 from "./routes/admin/index.tsx";
import * as $9 from "./routes/api/book.ts";
import * as $10 from "./routes/api/list.ts";
import * as $11 from "./routes/blog/[slug].tsx";
import * as $12 from "./routes/blog/index.tsx";
import * as $13 from "./routes/books/[id].tsx";
import * as $14 from "./routes/books/index.tsx";
import * as $15 from "./routes/callback.ts";
import * as $16 from "./routes/discover/index.tsx";
import * as $17 from "./routes/feed.ts";
import * as $18 from "./routes/index.tsx";
import * as $19 from "./routes/lists/[id].tsx";
import * as $20 from "./routes/lists/index.tsx";
import * as $21 from "./routes/login.ts";
import * as $22 from "./routes/logout.ts";
import * as $23 from "./routes/my-lists/_middleware.ts";
import * as $24 from "./routes/my-lists/index.tsx";
import * as $25 from "./routes/new-book/_middleware.ts";
import * as $26 from "./routes/new-book/index.tsx";
import * as $27 from "./routes/new-list/_middleware.ts";
import * as $28 from "./routes/new-list/index.tsx";
import * as $29 from "./routes/submit.tsx";
import * as $30 from "./routes/tracking/index.tsx";
import * as $31 from "./routes/uploaded-by-me-books/index.tsx";
import * as $32 from "./routes/uploads/ExampleTable.tsx";
import * as $33 from "./routes/uploads/index.tsx";
import * as $$0 from "./islands/Carousel.tsx";
import * as $$1 from "./islands/DeleteBookButton.tsx";
import * as $$2 from "./islands/DeleteListButton.tsx";
import * as $$3 from "./islands/EditBookForm.tsx";
import * as $$4 from "./islands/EditListForm.tsx";
import * as $$5 from "./islands/IpfsOpenButton.tsx";
import * as $$6 from "./islands/ListIpfsUploadButton.tsx";
import * as $$7 from "./islands/WantToReadList.tsx";
import * as $$8 from "./islands/Wrapper.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/account/_middleware.ts": $3,
    "./routes/account/index.tsx": $4,
    "./routes/account/manage.ts": $5,
    "./routes/account/upgrade.ts": $6,
    "./routes/admin/_middleware.ts": $7,
    "./routes/admin/index.tsx": $8,
    "./routes/api/book.ts": $9,
    "./routes/api/list.ts": $10,
    "./routes/blog/[slug].tsx": $11,
    "./routes/blog/index.tsx": $12,
    "./routes/books/[id].tsx": $13,
    "./routes/books/index.tsx": $14,
    "./routes/callback.ts": $15,
    "./routes/discover/index.tsx": $16,
    "./routes/feed.ts": $17,
    "./routes/index.tsx": $18,
    "./routes/lists/[id].tsx": $19,
    "./routes/lists/index.tsx": $20,
    "./routes/login.ts": $21,
    "./routes/logout.ts": $22,
    "./routes/my-lists/_middleware.ts": $23,
    "./routes/my-lists/index.tsx": $24,
    "./routes/new-book/_middleware.ts": $25,
    "./routes/new-book/index.tsx": $26,
    "./routes/new-list/_middleware.ts": $27,
    "./routes/new-list/index.tsx": $28,
    "./routes/submit.tsx": $29,
    "./routes/tracking/index.tsx": $30,
    "./routes/uploaded-by-me-books/index.tsx": $31,
    "./routes/uploads/ExampleTable.tsx": $32,
    "./routes/uploads/index.tsx": $33,
  },
  islands: {
    "./islands/Carousel.tsx": $$0,
    "./islands/DeleteBookButton.tsx": $$1,
    "./islands/DeleteListButton.tsx": $$2,
    "./islands/EditBookForm.tsx": $$3,
    "./islands/EditListForm.tsx": $$4,
    "./islands/IpfsOpenButton.tsx": $$5,
    "./islands/ListIpfsUploadButton.tsx": $$6,
    "./islands/WantToReadList.tsx": $$7,
    "./islands/Wrapper.tsx": $$8,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
